# Site settings
title: "Muhammad Ahmad's Digital Portfolio and Blog"
author: "Muhammad Ahmad"
description: "Welcome to my digital portfolio! I am excited to share my passion for science, technology and the world with you. As you explore my portfolio, you'll see that I have a wide range of interests and skills, which have allowed me to work on a variety of successful commercial projects. From designing websites to developing mobile apps, I enjoy taking on new challenges and pushing myself to grow as a developer. Thank you for taking the time!"
keywords: "Muslim, Software Engineering, Mathematics, Artificial Intelligence, React, React Native, Android, iOS, Mobile App Development, Website Development, Angular, Programming, Machine Learning, Artificial Intelligence, Deep Learning, Computer Vision"
biography: "I am currently a student studying <a href='https://courses.leeds.ac.uk/g734/computer-science-with-artificial-intelligence-meng-bsc'>Computer Science with Artificial Intelligence</a> at the <a href='https://www.leeds.ac.uk/'>University of Leeds</a>. Here you can find my <a href='/assets/AHMAD23-FINAL.pdf'>BSc Final Year Project Thesis</a> (not published yet) and my <a href='/assets/cv.pdf'>Résumé</a>."
colophon: "© Muhammad Ahmad. Site created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""
url: "http://muhammad-ahmad.tech"

twitter_username: Muhamma90215643
github_username: muhammadahmad1999
linkedin_username: muhammad-a-747540142
facebook_username: N/A
google-analytics: N/A

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
